#!/bin/sh
set -e
if [ -L /usr/bin/labelmaster ] || [ -f /usr/bin/labelmaster ]; then
    rm -f /usr/bin/labelmaster
fi
ln -s /opt/labelmaster/labelmaster.sh /usr/bin/labelmaster

if [ -L /bin/labelmaster ] || [ -f /bin/labelmaster ]; then
    rm -f /bin/labelmaster
fi
ln -s /opt/labelmaster/labelmaster.sh /bin/labelmaster

DESK=""
ICON="/usr/share/icons/hicolor/256x256/apps/labelmaster.png"
if [ -f "$ICON" ]; then
    	chown root:root "$ICON"
fi
if [ -f "DESK" ]; then
    	chown root:root "$DESK"
fi
if [ -d "/opt/labelmaster" ]; then
	chown -R root:root "/opt/labelmaster"
fi
update-desktop-database || true
update-icon-caches /usr/share/icons/hiclolor /usr/share/icons/hicolor/256x256/apps/labelmaster.png  || true
exit 0
